const librarys = [
  {
    id: 1,
    title: "خواجه تاجدار",
    author: "ژان گور",
    published_date: "۲۰۰۷ میلآدی" ,
    genre: "تاریخ",
    imgSrc: "./static/images/1.jpg",
  },
  {
    id: 2,
    title: "ضیافت",
    author: "افلاطون",
    published_date: "۱۷۹۵ میلآدی",
    genre: "فلسفه",
    imgSrc: "./static/images/2.jpg",
  },
  {
    id: 3,
    title: "منطق الطیر",
    author: "عطار نیشابوری",
    published_date: "۱۱۷۷ میلآدی",
    genre: "شعر",
    imgSrc: "./static/images/3.jpg",
  },
  {
    id: 4,
    title: "مثنوی معنوی",
    author: "مولانا",
    published_date: "۲۰۰۱ میلآدی",
    genre: "شعر",
    imgSrc: "./static/images/4.jpg",
  },
  {
    id: 5,
    title: "دیوان حاقظ",
    author: "حافظ",
    published_date: "۱۸۲۷ میلآدی",
    genre: "شعر",
    imgSrc: "./static/images/5.jpg",
  },
  {
    id: 6,
    title: "رومیو و جولیت",
    author: "ویلیام شکسپیر",
    published_date: "۱۵۹۷ میلآدی",
    genre: "عاشقانه",
    imgSrc: "./static/images/6.jpg",
  },
  {
    id: 7,
    title: "ویس و رامین",
    author: " فخرالدین اسعد گرگانی",
    published_date: "۲۰۲۱ میلآدی",
    genre: "عاشقانه",
    imgSrc: "./static/images/7.jpg",
  },
  {
    id: 8,
    title: "گلستان سعدی",
    author: "سعدی شیرازی",
    published_date: "۱۸۷۹ میلآدی",
    genre: "شعر",
    imgSrc: "./static/images/8.jpg",
  },
  {
    id: 9,
    title: "بوستان سعدی",
    author: "سعدی شیرازی",
    published_date: "۱۸۷۷ میلآدی",
    genre: "شعر",
    imgSrc: "./static/images/9.jpg",
  },
  {
    id: 10,
    title: "گلشن راز",
    author: "محمود شبستری",
    published_date: "۲۰۰۴ میلآدی",
    genre: "شعر",
    imgSrc: "./static/images/10.jpg",
  },
  {
    id: 11,
    title: "لیلی و مجنون ",
    author: "نظامی گنجوی",
    published_date: "۲۰۱۲ میلآدی",
    genre: "عاشقانه",
    imgSrc: "./static/images/11.jpg",
  },
  {
    id: 12,
    title: "شاهنامه فردوسی",
    author: "فردوسی",
    published_date: "۲۰۲۰ میلآدی",
    genre: "شعر",
    imgSrc: "./static/images/12.jpg",
  },
  {
    id: 13,
    title: "ایلاد",
    author: "هومر",
    published_date: "۲۰۱۷ میلآدی",
    genre: "شعر",
    imgSrc: "./static/images/13.jpg",
  },
  {
    id: 14,
    title: "اودیسه",
    author: "هومر",
    published_date: "۲۰۲۰ میلآدی",
    genre: "شعر",
    imgSrc: "./static/images/14.jpg",
  },
  {
    id: 15,
    title: "هملت",
    author: "شکسپیر",
    published_date: "۱۶۰۲ میلآدی",
    genre: "درام",
    imgSrc: "./static/images/15.jpg",
  },
  {
    id: 16,
    title: "دن کیشوت",
    author: "سراونتس",
    published_date: "۱۶۰۵ میلآدی",
    genre: "درام",
    imgSrc: "./static/images/16.jpg",
  },
];

// end
