const librarys = [
    {
      id: 1,
      title: "خواجه تاجدار",
      author: "ژان گور",
      published_date: "۱۳۸۶",
      genre: "تاریخ",
      imgSrc: "./images/1.jpg",
    },
    {
      id: 2,
      title: "ضیافت",
      author: "افلاطون",
      published_date: "۱۷۹۵",
      genre: "فلسفه",
      imgSrc: "./images/2.jpg",
    },
    {
      id: 3,
      title: "منطق الطیر",
      author: "عطار نیشابوری",
      published_date: "۱۱۷۷",
      genre: "شعر",
      imgSrc: "./images/3.jpg",
    },
    {
      id: 4,
      title: "مثنوی معنوی",
      author: "مولانا",
      published_date: "۲۰۰۱ میلادی",
      genre: "شعر",
      imgSrc: "./images/4.jpg",
    },
    {
      id: 5,
      title: "دیوان حاقظ",
      author: "حافظ",
      published_date: "۱۲۰۶",
      genre: "شعر",
      imgSrc: "./images/5.jpg",
    },
    {
      id: 6,
      title: "رومیو و جولیت",
      author: "ویلیام شکسپیر",
      published_date: "۱۵۹۷",
      genre: "عاشقانه",
      imgSrc: "./images/6.jpg",
    },
    {
      id: 7,
      title: "ویس و رامین",
      author: " فخرالدین اسعد گرگانی",
      published_date: "۲۰۲۱",
      genre: "عاشقانه",
      imgSrc: "./images/7.jpg",
    },
    {
      id: 8,
      title: "گلستان سعدی",
      author: "سعدی شیرازی",
      published_date: "۱۲۵۸",
      genre: "شعر",
      imgSrc: "./images/8.jpg",
    },
    {
      id: 9,
      title: "بوستان سعدی",
      author: "سعدی شیرازی",
      published_date: "۱۲۵۷",
      genre: "شعر",
      imgSrc: "./images/9.jpg",
    },
    {
      id: 10,
      title: "گلشن راز",
      author: "محمود شبستری",
      published_date: "۱۳۸۲",
      genre: "شعر",
      imgSrc: "./images/10.jpg",
    },
    {
      id: 11,
      title: "لیلی و مجنون ",
      author: "نظامی گنجوی",
      published_date: "۲۰۱۲",
      genre: "عاشقانه",
      imgSrc: "./images/11.jpg",
    },
    {
      id: 12,
      title: "شاهنامه فردوسی",
      author: "فردوسی",
      published_date: "۱۰۱۰",
      genre: "شعر",
      imgSrc: "./images/12.jpg",
    },
    {
      id: 13,
      title: "ایلاد",
      author: "هومر",
      published_date: "۱۳۹۶",
      genre: "شعر",
      imgSrc: "./images/13.jpg",
    },
    {
      id: 14,
      title: "اودیسه",
      author: "هومر",
      published_date: "۱۳۹۹",
      genre: "شعر",
      imgSrc: "./images/14.jpg",
    },
    {
      id: 15,
      title: "هملت",
      author: "شکسپیر",
      published_date: "۱۶۰۲",
      genre: "درام",
      imgSrc: "./images/15.jpg",
    },
    {
      id: 16,
      title: "دن کیشوت",
      author: "سراونتس",
      published_date: "۱۶۰۵",
      genre: "درام",
      imgSrc: "./images/16.jpg",
    },
  ];
  
  // end
  